name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools-version: '30.0.3'

      # Accept licenses
      - name: Accept licenses
        run: yes | sdkmanager --licenses

      # Diagnostic step: List all project files to locate gradlew
      - name: List all project files
        run: find . -name gradlew

      # Make gradlew executable if found
      - name: Make gradlew executable
        run: chmod +x ./gradlew || echo "gradlew not found, skipping chmod"

    
